# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('german_word', models.CharField(max_length=250)),
                ('english_translation', models.CharField(max_length=250)),
            ],
        ),
    ]
