# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='gender',
            field=models.CharField(default='der', max_length=4),
        ),
    ]
