# Generated by Django 2.1.5 on 2019-02-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_word_gender'),
    ]

    operations = [
            migrations.RenameField('Word', 'english_translation', 'translation'),
    ]
