# Generated by Django 2.1.5 on 2019-02-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190207_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='gender',
            field=models.CharField(default='Der', max_length=4),
        ),
    ]
