# Generated by Django 2.1.5 on 2019-03-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20190228_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vocbulary',
            new_name='vocabulary',
        ),
    ]
